spring.application.name=trade-risk-management-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/traderisk
spring.datasource.username=traderisk
spring.datasource.password=traderisk_local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true